set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN R2 [get_ports {led[0]}]
set_property PACKAGE_PIN R3 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN R4 [get_ports clk]
set_property PACKAGE_PIN U2 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[0]}]
set_property PACKAGE_PIN T3 [get_ports {gpio[0]}]
set_property PACKAGE_PIN Y2 [get_ports {gpio[1]}]


set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_n[0]}]
set_property PACKAGE_PIN J15 [get_ports {seg_sel_n[0]}]
set_property PACKAGE_PIN H17 [get_ports {seg_sel_n[1]}]
set_property PACKAGE_PIN H13 [get_ports {seg_sel_n[2]}]
set_property PACKAGE_PIN G17 [get_ports {seg_sel_n[3]}]
set_property PACKAGE_PIN H18 [get_ports {seg_sel_n[4]}]
set_property PACKAGE_PIN G18 [get_ports {seg_sel_n[5]}]
set_property PACKAGE_PIN H15 [get_ports {seg_data[0]}]
set_property PACKAGE_PIN L13 [get_ports {seg_data[2]}]
set_property PACKAGE_PIN G16 [get_ports {seg_data[1]}]
set_property PACKAGE_PIN G15 [get_ports {seg_data[3]}]
set_property PACKAGE_PIN K13 [get_ports {seg_data[4]}]
set_property PACKAGE_PIN G13 [get_ports {seg_data[5]}]
set_property PACKAGE_PIN H14 [get_ports {seg_data[6]}]
set_property PACKAGE_PIN J14 [get_ports {seg_data[7]}]





set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_d]
set_property PACKAGE_PIN U5 [get_ports uart_rx_d]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_0_inst/inst/clk_50m]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {inst_meme_waddr_o[0]} {inst_meme_waddr_o[1]} {inst_meme_waddr_o[2]} {inst_meme_waddr_o[3]} {inst_meme_waddr_o[4]} {inst_meme_waddr_o[5]} {inst_meme_waddr_o[6]} {inst_meme_waddr_o[7]} {inst_meme_waddr_o[8]} {inst_meme_waddr_o[9]} {inst_meme_waddr_o[10]} {inst_meme_waddr_o[11]} {inst_meme_waddr_o[12]} {inst_meme_waddr_o[13]} {inst_meme_waddr_o[14]} {inst_meme_waddr_o[15]} {inst_meme_waddr_o[16]} {inst_meme_waddr_o[17]} {inst_meme_waddr_o[18]} {inst_meme_waddr_o[19]} {inst_meme_waddr_o[20]} {inst_meme_waddr_o[21]} {inst_meme_waddr_o[22]} {inst_meme_waddr_o[23]} {inst_meme_waddr_o[24]} {inst_meme_waddr_o[25]} {inst_meme_waddr_o[26]} {inst_meme_waddr_o[27]} {inst_meme_waddr_o[28]} {inst_meme_waddr_o[29]} {inst_meme_waddr_o[30]} {inst_meme_waddr_o[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {inst_meme_wdata_o[0]} {inst_meme_wdata_o[1]} {inst_meme_wdata_o[2]} {inst_meme_wdata_o[3]} {inst_meme_wdata_o[4]} {inst_meme_wdata_o[5]} {inst_meme_wdata_o[6]} {inst_meme_wdata_o[7]} {inst_meme_wdata_o[8]} {inst_meme_wdata_o[9]} {inst_meme_wdata_o[10]} {inst_meme_wdata_o[11]} {inst_meme_wdata_o[12]} {inst_meme_wdata_o[13]} {inst_meme_wdata_o[14]} {inst_meme_wdata_o[15]} {inst_meme_wdata_o[16]} {inst_meme_wdata_o[17]} {inst_meme_wdata_o[18]} {inst_meme_wdata_o[19]} {inst_meme_wdata_o[20]} {inst_meme_wdata_o[21]} {inst_meme_wdata_o[22]} {inst_meme_wdata_o[23]} {inst_meme_wdata_o[24]} {inst_meme_wdata_o[25]} {inst_meme_wdata_o[26]} {inst_meme_wdata_o[27]} {inst_meme_wdata_o[28]} {inst_meme_wdata_o[29]} {inst_meme_wdata_o[30]} {inst_meme_wdata_o[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_riscv_0/if_id_curr_pc[0]} {u_riscv_0/if_id_curr_pc[1]} {u_riscv_0/if_id_curr_pc[2]} {u_riscv_0/if_id_curr_pc[3]} {u_riscv_0/if_id_curr_pc[4]} {u_riscv_0/if_id_curr_pc[5]} {u_riscv_0/if_id_curr_pc[6]} {u_riscv_0/if_id_curr_pc[7]} {u_riscv_0/if_id_curr_pc[8]} {u_riscv_0/if_id_curr_pc[9]} {u_riscv_0/if_id_curr_pc[10]} {u_riscv_0/if_id_curr_pc[11]} {u_riscv_0/if_id_curr_pc[12]} {u_riscv_0/if_id_curr_pc[13]} {u_riscv_0/if_id_curr_pc[14]} {u_riscv_0/if_id_curr_pc[15]} {u_riscv_0/if_id_curr_pc[16]} {u_riscv_0/if_id_curr_pc[17]} {u_riscv_0/if_id_curr_pc[18]} {u_riscv_0/if_id_curr_pc[19]} {u_riscv_0/if_id_curr_pc[20]} {u_riscv_0/if_id_curr_pc[21]} {u_riscv_0/if_id_curr_pc[22]} {u_riscv_0/if_id_curr_pc[23]} {u_riscv_0/if_id_curr_pc[24]} {u_riscv_0/if_id_curr_pc[25]} {u_riscv_0/if_id_curr_pc[26]} {u_riscv_0/if_id_curr_pc[27]} {u_riscv_0/if_id_curr_pc[28]} {u_riscv_0/if_id_curr_pc[29]} {u_riscv_0/if_id_curr_pc[30]} {u_riscv_0/if_id_curr_pc[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_riscv_0/if_id_inst[0]} {u_riscv_0/if_id_inst[1]} {u_riscv_0/if_id_inst[2]} {u_riscv_0/if_id_inst[3]} {u_riscv_0/if_id_inst[4]} {u_riscv_0/if_id_inst[5]} {u_riscv_0/if_id_inst[6]} {u_riscv_0/if_id_inst[7]} {u_riscv_0/if_id_inst[8]} {u_riscv_0/if_id_inst[9]} {u_riscv_0/if_id_inst[10]} {u_riscv_0/if_id_inst[11]} {u_riscv_0/if_id_inst[12]} {u_riscv_0/if_id_inst[13]} {u_riscv_0/if_id_inst[14]} {u_riscv_0/if_id_inst[15]} {u_riscv_0/if_id_inst[16]} {u_riscv_0/if_id_inst[17]} {u_riscv_0/if_id_inst[18]} {u_riscv_0/if_id_inst[19]} {u_riscv_0/if_id_inst[20]} {u_riscv_0/if_id_inst[21]} {u_riscv_0/if_id_inst[22]} {u_riscv_0/if_id_inst[23]} {u_riscv_0/if_id_inst[24]} {u_riscv_0/if_id_inst[25]} {u_riscv_0/if_id_inst[26]} {u_riscv_0/if_id_inst[27]} {u_riscv_0/if_id_inst[28]} {u_riscv_0/if_id_inst[29]} {u_riscv_0/if_id_inst[30]} {u_riscv_0/if_id_inst[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_riscv_0/if_id_next_pc[0]} {u_riscv_0/if_id_next_pc[1]} {u_riscv_0/if_id_next_pc[2]} {u_riscv_0/if_id_next_pc[3]} {u_riscv_0/if_id_next_pc[4]} {u_riscv_0/if_id_next_pc[5]} {u_riscv_0/if_id_next_pc[6]} {u_riscv_0/if_id_next_pc[7]} {u_riscv_0/if_id_next_pc[8]} {u_riscv_0/if_id_next_pc[9]} {u_riscv_0/if_id_next_pc[10]} {u_riscv_0/if_id_next_pc[11]} {u_riscv_0/if_id_next_pc[12]} {u_riscv_0/if_id_next_pc[13]} {u_riscv_0/if_id_next_pc[14]} {u_riscv_0/if_id_next_pc[15]} {u_riscv_0/if_id_next_pc[16]} {u_riscv_0/if_id_next_pc[17]} {u_riscv_0/if_id_next_pc[18]} {u_riscv_0/if_id_next_pc[19]} {u_riscv_0/if_id_next_pc[20]} {u_riscv_0/if_id_next_pc[21]} {u_riscv_0/if_id_next_pc[22]} {u_riscv_0/if_id_next_pc[23]} {u_riscv_0/if_id_next_pc[24]} {u_riscv_0/if_id_next_pc[25]} {u_riscv_0/if_id_next_pc[26]} {u_riscv_0/if_id_next_pc[27]} {u_riscv_0/if_id_next_pc[28]} {u_riscv_0/if_id_next_pc[29]} {u_riscv_0/if_id_next_pc[30]} {u_riscv_0/if_id_next_pc[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list inst_meme_we_o]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_50m]
